---
resolver: nightly-2025-03-11
packages:
  - ./example/
  - ./
ghc-options:
  "$locals":
    -Wall -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-deriving-strategies
    -Wmissing-export-lists
    -Wmissing-exported-signatures
    -Wmissing-home-modules
    -Wmissing-import-lists
    -Wpartial-fields
    -Wprepositive-qualified-module
    -Wredundant-constraints
    -Wunused-binds
    -Wunused-packages
    -Wunused-type-patterns
    -Wno-unticked-promoted-constructors
extra-deps:
  - env-guard-0.2@sha256:4251503bde7549e267bd307f4b293c8c0ac48c6585968108e3e3fc5a3cfbb179,1312
