name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "9.0.2"
          - "9.2.8"
          - "9.4.8"
          - "9.6.6"
          - "9.8.2"
          - "9.10.1"
          - "9.12.1"
        platform:
          - os: "macos-latest"
            set-env: "export"
          - os: "ubuntu-latest"
            set-env: "export"
          - os: "windows-latest"
            set-env: "set"
        # Evidently mac has trouble with these on CI now.
        exclude:
          - {ghc: "8.10.7", platform: {os: "macos-latest", set-env: "export"}}
          - {ghc: "9.0.2", platform: {os: "macos-latest", set-env: "export"}}
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Configure
        run: cabal configure --ghc-options -Werror

      - name: Compile
        run: cabal build gitrev

      - name: Test build example
        run: |
          .github/scripts/run_example_cabal_build.sh

      - name: Install exe
        run: |
          ${{ matrix.platform.set-env }} EXAMPLE_HOME=$(pwd); cabal install example --installdir=./build

      - name: Test installed example
        run: |
          .github/scripts/run_example_cabal_install.sh

      - name: Doctests
        # In general, doctests are flaky enough that I'm not too fussed about
        # having them run on all GHCs. One is enough to verify that the docs
        # are in pretty good shape.
        #
        # That said, we might as well support multiple versions when we do not
        # have to do any extra work.
        if: ${{ matrix.ghc == '9.10.1' || matrix.ghc == '9.12.1' }}
        run: |
          ./scripts/doctest.sh

  nix:
    strategy:
      fail-fast: false
      matrix:
        os:
        - "macos-latest"
        - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Compile & Test
        run: nix build

      - name: Build example
        run: nix build .#example

      - name: Test example
        run: |
          .github/scripts/run_example_nix.sh

  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Formatting
        run: |
          nix run .#format
          git diff --exit-code --color=always
